---
- name: "create directory"
  file: 
    path: /home/ubuntu/backend
    state: directory

- name: "move backend to server"
  synchronize: 
    src: ../../backend
    dest: /home/ubuntu

- name: "install dependencies."
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "start app"
  shell: "cd /home/ubuntu/backend && npm install && pm2 stop default && pm2 start npm -- start"
